import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "@/styles/globals.scss";

const notosans = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notosans.className}>{children}</body>
    </html>
  );
}
